# Generated by Django 6.0.1 on 2026-01-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('culture', models.TextField(blank=True)),
                ('ethnicity', models.TextField(blank=True)),
                ('best_time', models.CharField(blank=True, max_length=200)),
                ('how_to_reach', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/')),
            ],
        ),
    ]
